#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh
nitrogen --restore &

bspc monitor eDP1 -d I II III IV V VI VII VIII IX

bspc config border_width         2
bspc config window_gap           7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true



bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Spotify desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
